# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d70442f673be60f7f4b7e741302a4927e69c3f87251c869017746331bbd477f4d1a991c2822b06074d579bb181903c9a7aa69ec076e7ef1306973d065cd2dc9

test:
  secret_key_base: 95f981ad791b7dd853c06dd5dd2ade2000bfbbf355396e1c791357ee61778e9d65bb334e1a5a1168409633ef4ca9a6413b22572d474405ce5a4bd39431d7e309

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
